name: bioguard-api
region: nyc

services:
  - name: bioguard-api
    image:
      registry_type: GHCR
      registry: ghcr.io
      repository: lizperz/backend-bioguard
      digest: ${IMAGE_DIGEST}

    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs

    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    envs:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: ML_API_URL
        value: http://bioguard-ml:8080
      - key: WEB_APP_URL
        value: https://bioguard-web-6bgjx.ondigitalocean.app
      - key: MONGODB_CONNECTION_STRING
        value: ${MONGODB_CONNECTION_STRING}
        type: SECRET
      - key: JWT_SECRET_KEY
        value: ${JWT_SECRET_KEY}
        type: SECRET
      - key: GOOGLE_CLIENT_ID
        value: 512801602468-k4rab31tqithbjb4c36ltc4mad2sk4oj.apps.googleusercontent.com
        type: SECRET
      - key: STRIPE_SECRET_KEY
        value: ${STRIPE_SECRET_KEY}
        type: SECRET
      - key: PAYPAL_CLIENT_ID
        value: ${PAYPAL_CLIENT_ID}
        type: SECRET
      - key: FIREBASE_SERVER_KEY
        value: ${FIREBASE_SERVER_KEY}
        type: SECRET
      - key: SMTP_HOST
        value: ${SMTP_HOST}
        type: SECRET
      - key: SMTP_PORT
        value: ${SMTP_PORT}
        type: SECRET
      - key: SMTP_USER
        value: ${SMTP_USER}
        type: SECRET
      - key: SMTP_PASSWORD
        value: ${SMTP_PASSWORD}
        type: SECRET
      - key: SMTP_FROM
        value: ${SMTP_FROM}
        type: SECRET
      - key: SENDGRID_API_KEY
        value: ${SENDGRID_API_KEY}
        type: SECRET
      - key: FROM_EMAIL
        value: ${FROM_EMAIL}
        type: SECRET
      - key: FROM_NAME
        value: ${FROM_NAME}
        type: SECRET

  - name: bioguard-ml
    image:
      registry_type: GHCR
      registry: ghcr.io
      repository: lizperz/backend-bioguard-ml
      digest: ${ML_IMAGE_DIGEST}

    instance_count: 1
    instance_size_slug: basic-xxs

    internal_ports:
      - 8000

    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
